runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

skip_files:
# default
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# end of default
- ^node_modules$
- ^(.*/)?\.jsx$
- ^(.*/)?\LICENSE$
- ^(.*/)?\package.json$
- ^(.*/)?\README.md$
- ^(.*/)?\webpack.config.js$


